name: shiheng_oa
description: "时恒电子移动办公平台"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: any
  dio: any
  get: any
  get_storage: any
  flutter_screenutil: any
  flutter_svg: any
  cached_network_image: any
  intl: any
  fl_chart: any
  shimmer: ^2.0.0
  flutter_staggered_grid_view: any
  pull_to_refresh: any
  flutter_smart_dialog: any
  mobile_scanner: ^5.2.3
  flutter_bmflocation: ^3.8.4
  amap_flutter_location: ^3.0.0
  permission_handler: ^11.0.0
  getuiflut: ^0.2.31
  emoji_picker_flutter: ^2.1.0
  lpinyin: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
